#!/usr/bin/env node
// Bot Arena (headless): calibrate the app's 11 bot levels by playing them
// against each other and fitting Elo ratings from the results.
//
//   node scripts/calibrate-levels.mjs [--games 6] [--parallel 3] [--levels 1-11]
//                                     [--out src/level-ratings.js] [--results results.json]
//                                     [--seed earlier.json] [--offset 3]
//   node scripts/calibrate-levels.mjs --fit results.json      # refit without playing
//
// --seed adds the games of an earlier run to this one (more games = tighter
// ratings); --offset starts the opening list further along so the new games
// don't repeat the openings of the seeded ones.
//
// Every level is played with EXACTLY the settings the app uses (Skill Level +
// depth cap; see src/config.js), from paired openings with colours swapped.
// The fitted scale is relative (levels against each other) and anchored so its
// mean equals the mean of the nominal Elo labels — it tells players how the
// levels rank and how far apart they are, it is not a FIDE rating.
//
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Chess } from 'chess.js';

import { LEVELS } from '../src/config.js';
import { enforceIncreasing, fitRatings, pairSchedule } from '../src/rating.js';
import { ROOT, UciEngine, prepareEngineDir } from './uci-node.mjs';

// Sound, varied 4-ply openings; a game and its colour-swapped twin share one.
export const OPENINGS = [
  'e4 e5 Nf3 Nc6', 'e4 c5 Nf3 d6', 'd4 d5 c4 e6', 'd4 Nf6 c4 g6',
  'e4 e6 d4 d5', 'c4 e5 Nc3 Nf6', 'Nf3 d5 g3 Nf6', 'e4 c6 d4 d5',
];

/**
 * Result adjudication so decided games don't play out to the end: white wins
 * when the last four evaluations (white's point of view, in centipawns) are all
 * >= +600, black when all <= -600; a long dead-equal endgame is drawn.
 * @param {number[]} whiteEvals  white-POV eval after each ply so far
 * @returns {'1-0'|'0-1'|'1/2-1/2'|null}
 */
export function adjudicate(whiteEvals) {
  const last4 = whiteEvals.slice(-4);
  if (last4.length === 4 && last4.every((e) => e >= 600)) return '1-0';
  if (last4.length === 4 && last4.every((e) => e <= -600)) return '0-1';
  const last12 = whiteEvals.slice(-12);
  if (whiteEvals.length >= 120 && last12.length === 12 && last12.every((e) => Math.abs(e) <= 25)) return '1/2-1/2';
  return null;
}

/** One bot with the exact settings the app gives a level (see src/config.js). */
async function createBot(engineDir, level) {
  const engine = new UciEngine(engineDir);
  await engine.init({ 'Skill Level': level.skill, Hash: 16 });
  return {
    /** Best move + the engine's own eval (side to move, centipawns). */
    choose: (fen) => engine.search(fen, `depth ${level.depth} movetime ${level.movetime}`),
    quit: () => engine.quit(),
  };
}

async function playGame(engineDir, whiteLevel, blackLevel, opening) {
  const [white, black] = await Promise.all([createBot(engineDir, whiteLevel), createBot(engineDir, blackLevel)]);
  const game = new Chess();
  for (const san of opening.split(' ')) game.move(san);
  const whiteEvals = [];
  let result = null;
  while (!game.isGameOver() && game.history().length < 220 && !result) {
    const mover = game.turn() === 'w' ? white : black;
    const { move, score } = await mover.choose(game.fen());
    if (!move || move === '(none)') break;
    game.move({ from: move.slice(0, 2), to: move.slice(2, 4), promotion: move[4] });
    whiteEvals.push(game.turn() === 'b' ? score : -score); // score is from the mover's side
    result = adjudicate(whiteEvals);
  }
  white.quit();
  black.quit();
  if (result) return { result, plies: game.history().length };
  if (game.isCheckmate()) return { result: game.turn() === 'w' ? '0-1' : '1-0', plies: game.history().length };
  return { result: '1/2-1/2', plies: game.history().length };
}

function parseArgs(argv) {
  const args = { games: 6, parallel: 3, levels: '1-11', out: join(ROOT, 'src/level-ratings.js'), results: null, fit: null, seed: null, offset: 0 };
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i].replace(/^--/, '');
    args[key] = argv[i + 1];
  }
  args.games = Number(args.games);
  args.parallel = Number(args.parallel);
  args.offset = Number(args.offset);
  return args;
}

function parseLevels(spec) {
  const [from, to] = String(spec).split('-').map(Number);
  return Array.from({ length: (to ?? from) - from + 1 }, (_, i) => from + i);
}

function writeRatingsModule(path, { ratings, games, gamesPerPair, results }) {
  const body = `// Generated by scripts/calibrate-levels.mjs — do not edit by hand.
// Relative ratings from ${games} bot-vs-bot games (${gamesPerPair} per scheduled pair, colours
// swapped, same settings as the app). Anchored to the mean of the nominal labels.
export const LEVEL_RATINGS = ${JSON.stringify({
    generatedAt: new Date().toISOString().slice(0, 10), games, gamesPerPair, ratings,
  }, null, 2)};
`;
  writeFileSync(path, body);
  return results;
}

export function scoreOf(result, aIsWhite) {
  if (result === '1/2-1/2') return 0.5;
  return (result === '1-0') === aIsWhite ? 1 : 0;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const levelNumbers = parseLevels(args.levels);
  const anchorMean = levelNumbers.reduce((s, n) => s + LEVELS[n - 1].nominal, 0) / levelNumbers.length;

  let results = args.seed ? JSON.parse(readFileSync(args.seed, 'utf8')) : [];
  if (args.fit) {
    results = JSON.parse(readFileSync(args.fit, 'utf8'));
  } else {
    const engineDir = prepareEngineDir();

    const jobs = [];
    for (const [a, b] of pairSchedule(levelNumbers, 2)) {
      for (let g = 0; g < args.games; g++) {
        jobs.push({ a, b, opening: OPENINGS[(Math.floor(g / 2) + args.offset) % OPENINGS.length], aIsWhite: g % 2 === 0 });
      }
    }
    console.log(`${jobs.length} games, ${args.parallel} at a time`);
    let next = 0;
    let done = 0;
    const worker = async () => {
      while (next < jobs.length) {
        const job = jobs[next++];
        const white = LEVELS[(job.aIsWhite ? job.a : job.b) - 1];
        const black = LEVELS[(job.aIsWhite ? job.b : job.a) - 1];
        const { result, plies } = await playGame(engineDir, white, black, job.opening);
        results.push({ a: job.a, b: job.b, score: scoreOf(result, job.aIsWhite), plies, result });
        done += 1;
        console.log(`[${done}/${jobs.length}] L${job.a} vs L${job.b} ${job.aIsWhite ? '(a=white)' : '(a=black)'} ${result} in ${plies} plies`);
        if (args.results) writeFileSync(args.results, JSON.stringify(results));
      }
    };
    await Promise.all(Array.from({ length: args.parallel }, worker));
    if (args.results) writeFileSync(args.results, JSON.stringify(results));
  }

  // Levels are built to get stronger; sampling noise must not reorder them.
  const fitted = fitRatings(results, { levels: levelNumbers, anchorMean });
  const ordered = enforceIncreasing(levelNumbers.map((n) => fitted[n]));
  const ratings = Object.fromEntries(levelNumbers.map((n, i) => [n, Math.round(ordered[i] / 10) * 10]));
  console.log('\nlevel  nominal  calibrated');
  for (const n of levelNumbers) console.log(String(n).padStart(5), String(LEVELS[n - 1].nominal).padStart(8), String(ratings[n]).padStart(11));
  const pairCount = pairSchedule(levelNumbers, 2).length;
  writeRatingsModule(args.out, { ratings, games: results.length, gamesPerPair: Math.round(results.length / pairCount), results });
  console.log(`\nwrote ${args.out}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main().catch((error) => { console.error(error); process.exit(1); });
}
