// Generated by scripts/calibrate-levels.mjs — do not edit by hand.
// Relative ratings from 304 bot-vs-bot games (16 per scheduled pair, colours
// swapped, same settings as the app). Anchored to the mean of the nominal labels.
export const LEVEL_RATINGS = {
  "generatedAt": "2026-09-28",
  "games": 304,
  "gamesPerPair": 16,
  "ratings": {
    "1": 700,
    "2": 1190,
    "3": 1300,
    "4": 1440,
    "5": 1670,
    "6": 1760,
    "7": 1950,
    "8": 2260,
    "9": 2430,
    "10": 2500,
    "11": 2610
  }
};
